spring:
  boot:
    admin:
      url: http://localhost:8080
      username: "${security.user.name}"
      password: "${security.user.password}"
      routes:
        endpoints: metrics,info,trace,logfile,loggers,hystrix.stream,mappings
    
security:
  user:
    name: admin
    password: admin
