server:
  port: 8080
  
logging:
  file: log.log
  level:
    com:
      netflix:
        discovery:
          internal:
            util:
              Archaius1Utils: ERROR
          endpoint:
            EndpointUtils: ERROR
            
spring:
  datasource:
    name: test
    url: jdbc:hsqldb:mem:test://localhost/test
    username:
    password: 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: none
      
eureka:
  instance:
    healthCheckUrlPath: ${management.contextPath}/health
    metadata-map:
      management.context-path: "${management.contextPath}"
  client:
    serviceUrl:
      defaultZone: http://admin:admin@ec2-13-59-80-6.us-east-2.compute.amazonaws.com:8761/eureka/
            
management:
  contextPath: /mgmt
  security:
    enabled: false
    
endpoints:
  enabled: false
  health.enabled: true
  info.enabled: true
  logfile.enabled: true
  loggers.enabled: true
  metrics.enabled: true
  trace.enabled: true
  
---
   
spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost
    port: 8761
    healthCheckUrlPath: ${management.contextPath}/health
    metadata-map:
      management.context-path: "${management.contextPath}"
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
